apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "go-httpbin.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "go-httpbin.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "go-httpbin.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "skyscanner/go-httpbin:6bcdbda6"
        imagePullPolicy: IfNotPresent
        env:
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        ports:
        - containerPort: 8080
          name: {{ template "go-httpbin.name" . }}
          protocol: TCP

