{{- $serviceName := include "go-httpbin.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "go-httpbin.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "go-httpbin.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: ara
    array.service.tyk.io/tags: "[\"ingress\",\"edge\"]"
    string.service.tyk.io/proxy.listen_path: "/httpbin"
    string.service.tyk.io/domain: ""
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: 8080
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
